### ISSUE TITLE
Prettified Tree Printing

### ISSUE THREAD

**Issue by jalextowle** [jalextowle/solidity-fix#14]
## Description
Currently the parse tree representation is hard to read. Something that would be nice to have is a printing function implemented for the parse tree. 

## Bonus
Implement this as a trait, and implement the trait for `ParseTree` and `ParseNode`.

**Comment by wadealexc** [comment]
This can be achieved with the Debug trait. Example:

`println!("Tree: {:#?}", tree);`

Where `:#?` uses Debug's prettified-printing!

**Comment by jalextowle** [comment]
@wadeAlexC Okay, that is extremely useful. I'll integrate that into the main function of the stylize PR, so that when that PR gets merged we will have pretty printing (unless you've already made this change).
